import { readFileSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import {
  OPENAI_COMPATIBLE_API_KEY_ENV_VAR,
  OPENAI_COMPATIBLE_BASE_URL_ENV_VAR,
  OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID,
  OPENAI_COMPATIBLE_EXTRACTION_ENV_VAR,
  OPENAI_COMPATIBLE_EXTRACTION_PROVIDER_CONFIG_ID_ENV_VAR,
  OPENAI_COMPATIBLE_FINAL_AUDIT_PROVIDER_CONFIG_ID_ENV_VAR,
  OPENAI_COMPATIBLE_FINAL_CANDIDATE_PROVIDER_CONFIG_ID_ENV_VAR,
  OPENAI_COMPATIBLE_FINALIZATION_ENV_VAR,
  OPENAI_COMPATIBLE_MODEL_ENV_VAR,
  OPENAI_COMPATIBLE_PROFILE_ENV_VAR,
  OPENAI_COMPATIBLE_REVIEW_ENV_VAR,
  OPENAI_COMPATIBLE_REVIEW_PROVIDER_CONFIG_ID_ENV_VAR
} from "./openai-compatible-profile";

export const OPENAI_COMPATIBLE_SETUP_ENV_BEGIN =
  "# BEGIN DELIBERUM OPENAI-COMPATIBLE WEB SETUP" as const;
export const OPENAI_COMPATIBLE_SETUP_ENV_END =
  "# END DELIBERUM OPENAI-COMPATIBLE WEB SETUP" as const;
export const DEFAULT_DAEMON_SETUP_ENV_FILE_PATH = ".env" as const;

export type OpenAICompatibleSetupInput = {
  apiKey: unknown;
  baseUrl: unknown;
  model: unknown;
};

export type OpenAICompatibleSetupResult = {
  profileId: "openai-compatible";
  status: "saved";
  managedEnvFile: "local-daemon-env";
  configuredFields: Array<"apiKey" | "baseUrl" | "model">;
  restartRequired: boolean;
  activeInCurrentDaemon: boolean;
  safety: string[];
};

export type ManagedDaemonSetupEnvLoadResult = {
  filePath: string;
  loaded: boolean;
  appliedEnvVars: string[];
  skippedEnvVars: string[];
};

export class SetupEnvError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "SetupEnvError";
    this.code = code;
  }
}

export async function writeOpenAICompatibleSetupEnv(input: {
  envFilePath?: string;
  activeEnv?: Record<string, string | undefined>;
  setup: OpenAICompatibleSetupInput;
}): Promise<OpenAICompatibleSetupResult> {
  const envFilePath = input.envFilePath ?? DEFAULT_DAEMON_SETUP_ENV_FILE_PATH;
  const setup = normalizeOpenAICompatibleSetup(input.setup);
  const block = createOpenAICompatibleSetupBlock(setup);
  const existingContent = await readOptionalTextFile(envFilePath);
  const nextContent = mergeDaemonEnvBlock(existingContent, block);

  await writeFile(envFilePath, nextContent, "utf8");

  if (input.activeEnv) {
    applyOpenAICompatibleSetupToEnv(input.activeEnv, setup);
  }

  const activeInCurrentDaemon = input.activeEnv !== undefined;

  return {
    profileId: "openai-compatible",
    status: "saved",
    managedEnvFile: "local-daemon-env",
    configuredFields: ["apiKey", "baseUrl", "model"],
    restartRequired: !activeInCurrentDaemon,
    activeInCurrentDaemon,
    safety: activeInCurrentDaemon
      ? [
          "The API key was written to the local daemon env file but is not returned.",
          "The setup was applied to the current local daemon process.",
          "The daemon will also load the managed local setup block on the next start."
        ]
      : [
          "The API key was written to the local daemon env file but is not returned.",
          "The daemon loads the managed local setup block at startup.",
          "Restart the local daemon, then refresh Web to verify readiness."
        ]
  };
}

export function applyOpenAICompatibleSetupToEnv(
  env: Record<string, string | undefined>,
  setup: OpenAICompatibleSetupInput
): void {
  applyNormalizedOpenAICompatibleSetupToEnv(
    env,
    normalizeOpenAICompatibleSetup(setup)
  );
}

export function loadManagedDaemonSetupEnvFile(input: {
  envFilePath?: string;
  env?: Record<string, string | undefined>;
} = {}): ManagedDaemonSetupEnvLoadResult {
  const envFilePath = input.envFilePath ?? DEFAULT_DAEMON_SETUP_ENV_FILE_PATH;
  const env = input.env ?? process.env;
  const existingContent = readOptionalTextFileSync(envFilePath);
  const assignments =
    existingContent === undefined ? undefined : parseManagedDaemonEnvBlock(existingContent);
  const appliedEnvVars: string[] = [];
  const skippedEnvVars: string[] = [];

  if (!assignments) {
    return {
      filePath: envFilePath,
      loaded: false,
      appliedEnvVars,
      skippedEnvVars
    };
  }

  for (const [name, value] of assignments) {
    if (!isManagedSetupEnvVar(name)) {
      skippedEnvVars.push(name);
      continue;
    }

    if (env[name]?.trim()) {
      skippedEnvVars.push(name);
      continue;
    }

    env[name] = value;
    appliedEnvVars.push(name);
  }

  return {
    filePath: envFilePath,
    loaded: true,
    appliedEnvVars,
    skippedEnvVars
  };
}

function createOpenAICompatibleSetupBlock(input: {
  apiKey: string;
  baseUrl: string;
  model: string;
}): string {
  return `${[
    OPENAI_COMPATIBLE_SETUP_ENV_BEGIN,
    "# Deliberum OpenAI-compatible provider setup",
    "# Generated by local Web setup.",
    "# Keep this file local. Do not commit provider credentials.",
    `${OPENAI_COMPATIBLE_PROFILE_ENV_VAR}=true`,
    `${OPENAI_COMPATIBLE_EXTRACTION_ENV_VAR}=true`,
    `${OPENAI_COMPATIBLE_REVIEW_ENV_VAR}=true`,
    `${OPENAI_COMPATIBLE_FINALIZATION_ENV_VAR}=true`,
    `${OPENAI_COMPATIBLE_EXTRACTION_PROVIDER_CONFIG_ID_ENV_VAR}=${OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID}`,
    `${OPENAI_COMPATIBLE_REVIEW_PROVIDER_CONFIG_ID_ENV_VAR}=${OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID}`,
    `${OPENAI_COMPATIBLE_FINAL_CANDIDATE_PROVIDER_CONFIG_ID_ENV_VAR}=${OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID}`,
    `${OPENAI_COMPATIBLE_FINAL_AUDIT_PROVIDER_CONFIG_ID_ENV_VAR}=${OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID}`,
    `${OPENAI_COMPATIBLE_BASE_URL_ENV_VAR}=${formatEnvAssignmentValue(input.baseUrl)}`,
    `${OPENAI_COMPATIBLE_MODEL_ENV_VAR}=${formatEnvAssignmentValue(input.model)}`,
    `${OPENAI_COMPATIBLE_API_KEY_ENV_VAR}=${formatEnvAssignmentValue(input.apiKey)}`,
    OPENAI_COMPATIBLE_SETUP_ENV_END
  ].join("\n")}\n`;
}

function normalizeOpenAICompatibleSetup(input: OpenAICompatibleSetupInput): {
  apiKey: string;
  baseUrl: string;
  model: string;
} {
  return {
    apiKey: normalizeSecretValue(input.apiKey, "API key"),
    baseUrl: normalizeOpenAICompatibleBaseUrlValue(input.baseUrl),
    model: normalizeNonSecretTextValue(input.model, "Model")
  };
}

function applyNormalizedOpenAICompatibleSetupToEnv(
  env: Record<string, string | undefined>,
  setup: {
    apiKey: string;
    baseUrl: string;
    model: string;
  }
): void {
  env[OPENAI_COMPATIBLE_PROFILE_ENV_VAR] = "true";
  env[OPENAI_COMPATIBLE_EXTRACTION_ENV_VAR] = "true";
  env[OPENAI_COMPATIBLE_REVIEW_ENV_VAR] = "true";
  env[OPENAI_COMPATIBLE_FINALIZATION_ENV_VAR] = "true";
  env[OPENAI_COMPATIBLE_EXTRACTION_PROVIDER_CONFIG_ID_ENV_VAR] =
    OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID;
  env[OPENAI_COMPATIBLE_REVIEW_PROVIDER_CONFIG_ID_ENV_VAR] =
    OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID;
  env[OPENAI_COMPATIBLE_FINAL_CANDIDATE_PROVIDER_CONFIG_ID_ENV_VAR] =
    OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID;
  env[OPENAI_COMPATIBLE_FINAL_AUDIT_PROVIDER_CONFIG_ID_ENV_VAR] =
    OPENAI_COMPATIBLE_DEFAULT_PROVIDER_CONFIG_ID;
  env[OPENAI_COMPATIBLE_BASE_URL_ENV_VAR] = setup.baseUrl;
  env[OPENAI_COMPATIBLE_MODEL_ENV_VAR] = setup.model;
  env[OPENAI_COMPATIBLE_API_KEY_ENV_VAR] = setup.apiKey;
}

function mergeDaemonEnvBlock(existingContent: string | undefined, block: string): string {
  if (existingContent === undefined || existingContent.trim().length === 0) {
    return block;
  }

  const beginIndex = existingContent.indexOf(OPENAI_COMPATIBLE_SETUP_ENV_BEGIN);
  const endIndex = existingContent.indexOf(OPENAI_COMPATIBLE_SETUP_ENV_END);

  if (beginIndex === -1 && endIndex === -1) {
    const separator = existingContent.endsWith("\n") ? "\n" : "\n\n";
    return `${existingContent}${separator}${block}`;
  }

  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
    throw new SetupEnvError(
      "setup_env_file_invalid",
      "The local env file contains an incomplete Deliberum OpenAI-compatible Web setup block."
    );
  }

  const replacementEndIndex = endIndex + OPENAI_COMPATIBLE_SETUP_ENV_END.length;
  const before = existingContent.slice(0, beginIndex);
  const after = existingContent.slice(replacementEndIndex).replace(/^\r?\n/, "");
  const separator = before.length > 0 && !before.endsWith("\n") ? "\n" : "";

  return `${before}${separator}${block}${after}`;
}

async function readOptionalTextFile(filePath: string): Promise<string | undefined> {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (isNodeFileNotFoundError(error)) {
      return undefined;
    }

    throw error;
  }
}

function readOptionalTextFileSync(filePath: string): string | undefined {
  try {
    return readFileSync(filePath, "utf8");
  } catch (error) {
    if (isNodeFileNotFoundError(error)) {
      return undefined;
    }

    throw error;
  }
}

function parseManagedDaemonEnvBlock(content: string): Map<string, string> | undefined {
  const beginIndex = content.indexOf(OPENAI_COMPATIBLE_SETUP_ENV_BEGIN);
  const endIndex = content.indexOf(OPENAI_COMPATIBLE_SETUP_ENV_END);

  if (beginIndex === -1 && endIndex === -1) {
    return undefined;
  }

  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
    throw new SetupEnvError(
      "setup_env_file_invalid",
      "The local env file contains an incomplete Deliberum OpenAI-compatible Web setup block."
    );
  }

  const blockBody = content.slice(
    beginIndex + OPENAI_COMPATIBLE_SETUP_ENV_BEGIN.length,
    endIndex
  );
  const assignments = new Map<string, string>();

  for (const line of blockBody.split(/\r?\n/)) {
    const trimmed = line.trim();

    if (trimmed.length === 0 || trimmed.startsWith("#")) {
      continue;
    }

    const separatorIndex = trimmed.indexOf("=");
    if (separatorIndex <= 0) {
      throw new SetupEnvError(
        "setup_env_file_invalid",
        "The local env file contains an invalid Deliberum managed assignment."
      );
    }

    const name = trimmed.slice(0, separatorIndex).trim();
    const rawValue = trimmed.slice(separatorIndex + 1).trim();

    if (!/^[A-Z0-9_]+$/.test(name)) {
      throw new SetupEnvError(
        "setup_env_file_invalid",
        "The local env file contains an invalid Deliberum managed variable name."
      );
    }

    assignments.set(name, parseEnvAssignmentValue(rawValue));
  }

  return assignments;
}

function normalizeSecretValue(value: unknown, label: string): string {
  const normalized = normalizeTextValue(value, label);

  if (normalized.length < 8) {
    throw new SetupEnvError(
      "setup_value_invalid",
      `${label} must be at least 8 characters.`
    );
  }

  return normalized;
}

function normalizeHttpUrlValue(value: unknown, label: string): string {
  const normalized = normalizeNonSecretTextValue(value, label);
  let parsed: URL;

  try {
    parsed = new URL(normalized);
  } catch {
    throw new SetupEnvError("setup_value_invalid", `${label} must be a valid URL.`);
  }

  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new SetupEnvError("setup_value_invalid", `${label} must use http or https.`);
  }

  return normalized;
}

function normalizeOpenAICompatibleBaseUrlValue(value: unknown): string {
  const normalized = normalizeHttpUrlValue(value, "Base URL");
  const parsed = new URL(normalized);

  if (
    (parsed.pathname === "/v1" || parsed.pathname === "/v1/") &&
    parsed.search === "" &&
    parsed.hash === ""
  ) {
    parsed.pathname = "/";
    return stripTrailingSlash(parsed.toString());
  }

  return normalized;
}

function stripTrailingSlash(value: string): string {
  return value.endsWith("/") ? value.slice(0, -1) : value;
}

function normalizeNonSecretTextValue(value: unknown, label: string): string {
  const normalized = normalizeTextValue(value, label);

  if (containsSecretLikeValue(normalized)) {
    throw new SetupEnvError(
      "setup_value_invalid",
      `${label} must not contain secret-like material.`
    );
  }

  return normalized;
}

function normalizeTextValue(value: unknown, label: string): string {
  if (typeof value !== "string") {
    throw new SetupEnvError("setup_value_invalid", `${label} must be a string.`);
  }

  const normalized = value.trim();

  if (normalized.length === 0) {
    throw new SetupEnvError("setup_value_invalid", `${label} is required.`);
  }

  if (normalized.length > 2048) {
    throw new SetupEnvError("setup_value_invalid", `${label} is too long.`);
  }

  if (/[\r\n]/.test(normalized)) {
    throw new SetupEnvError("setup_value_invalid", `${label} must be a single line.`);
  }

  return normalized;
}

function formatEnvAssignmentValue(value: string): string {
  if (/^[A-Za-z0-9_./:@+-]+$/.test(value)) {
    return value;
  }

  return JSON.stringify(value);
}

function parseEnvAssignmentValue(value: string): string {
  if (value.startsWith("\"")) {
    let parsed: unknown;

    try {
      parsed = JSON.parse(value) as unknown;
    } catch {
      throw new SetupEnvError(
        "setup_env_file_invalid",
        "The local env file contains an invalid quoted Deliberum managed value."
      );
    }

    if (typeof parsed !== "string") {
      throw new SetupEnvError(
        "setup_env_file_invalid",
        "The local env file contains an invalid quoted Deliberum managed value."
      );
    }

    return parsed;
  }

  return value;
}

function isManagedSetupEnvVar(name: string): boolean {
  return (
    name === OPENAI_COMPATIBLE_PROFILE_ENV_VAR ||
    name === OPENAI_COMPATIBLE_EXTRACTION_ENV_VAR ||
    name === OPENAI_COMPATIBLE_REVIEW_ENV_VAR ||
    name === OPENAI_COMPATIBLE_FINALIZATION_ENV_VAR ||
    name === OPENAI_COMPATIBLE_EXTRACTION_PROVIDER_CONFIG_ID_ENV_VAR ||
    name === OPENAI_COMPATIBLE_REVIEW_PROVIDER_CONFIG_ID_ENV_VAR ||
    name === OPENAI_COMPATIBLE_FINAL_CANDIDATE_PROVIDER_CONFIG_ID_ENV_VAR ||
    name === OPENAI_COMPATIBLE_FINAL_AUDIT_PROVIDER_CONFIG_ID_ENV_VAR ||
    name === OPENAI_COMPATIBLE_BASE_URL_ENV_VAR ||
    name === OPENAI_COMPATIBLE_MODEL_ENV_VAR ||
    name === OPENAI_COMPATIBLE_API_KEY_ENV_VAR
  );
}

function containsSecretLikeValue(value: string): boolean {
  return /api[_-]?key|secret|private[_-]?token|access[_-]?token|authorization|bearer|sk-[a-z0-9]/i.test(
    value
  );
}

function isNodeFileNotFoundError(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: unknown }).code === "ENOENT"
  );
}
